# ----------------------------------------------------------------------------
# GitHub Action workflow to build using latest Castle Game Engine snapshot
# for multiple platforms.
#
# Uses CGE Docker image https://hub.docker.com/r/kambi/castle-engine-cloud-builds-tools/ .
# Uses GitHub-hosted runners, i.e. you don't need to set up any server infrastructure,
# GitHub provides it all for free for open-source projects.
#
# See https://docs.github.com/en/actions for docs.
#
# TODO: wrap in new GH action,
# https://docs.github.com/en/actions/creating-actions/about-custom-actions
#
# ----------------------------------------------------------------------------

name: Build
on: [push]

jobs:
  build-windows:
    name: Build Windows
    runs-on: ubuntu-latest
    container: kambi/castle-engine-cloud-builds-tools:cge-none
    steps:
      - uses: actions/checkout@v2
      # Set env CASTLE_ENGINE_PATH following
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
      # https://brandur.org/fragments/github-actions-env-vars-in-env-vars
      - name: Castle Game Engine - Setup environment
        run: echo "CASTLE_ENGINE_PATH=$GITHUB_WORKSPACE/castle-engine" >> $GITHUB_ENV
      - name: Castle Game Engine - Clone snapshot
        run: git clone --depth 1 --single-branch --branch snapshot https://github.com/castle-engine/castle-engine/
      - name: Castle Game Engine - Build
        run: cd $CASTLE_ENGINE_PATH/tools/build-tool/ && ./castle-engine_compile.sh
      - name: Package
        run: $CASTLE_ENGINE_PATH/tools/build-tool/castle-engine package --os=win64 --cpu=x86_64 --verbose
      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: \*-win64-x86_64.zip
